### ISSUE TITLE
Add on the README info about how to execute the tests

### ISSUE THREAD

**Issue by avraam-mavridis-sociomantic** [sociomantic/microbe#102]
Missing info on the README file about the test execution. 
Add info about that both for the on-console and on-browser test runner.

**Comment by avraam-mavridis-sociomantic** [comment]
@jason-braun-sociomantic-mouse  This probably can be an issue for the @yourfirstpr

**Comment by jason-braun-sociomantic-mouse** [comment]
+1  i love it
(unless you want it) I can do this tonight or in the morning

**Comment by AvraamMavridis** [comment]
@jason-braun-sociomantic-mouse nope you can do it :), I think is better to be an issue for @yourfirstpr, I just wanted to write some tests about `include` and spotted that there is nothing related about tests on README.

**Comment by jason-braun-sociomantic-mouse** [comment]
yup.  i meant setting up the issue, not doing it.  It's totally a @yourfirstPR issue

**Comment by avraam-mavridis-sociomantic** [comment]
I close this because -> https://github.com/sociomantic/microbe/issues/103

**Comment by jason-braun-sociomantic-mouse** [comment]
🌮
