### ISSUE TITLE
README: Add info about how to execute the tests 

### ISSUE THREAD

**Issue by mousemke** [sociomantic/microbe#103]
In the spirit of learning how to use Git and Pull requests (PRs) <a href="https://twitter.com/yourfirstpr" target="_blank">@yourfirstpr</a>, this issue should be approachable for anyone. This should be a fairly straight forward change and will not effect the UI or functionality of the component. It's what we'd consider a "no harm" change. Here's what you need to do:

1 ) Fork the repo
2 ) Clone the repo to your local machine
3 ) Switch to the ReadmeTestFix branch
3 ) Open up README.md in your favorite editor
4 ) Add the instructions (below)
5 ) Commit your changes to the file
5 ) Pull the repo.  This makes sure your branch is up to date before pushing your changes.
6 ) Push your changes to your fork
7 ) Create a PR and include Fixes #103 in the message
8 ) Get merged and celebrate :tada:

The Change
=========

In ./README.md, right above the `Generating www docs` section, add:

```
    Running the tests
    =================

    From the command line:

    ```
    npm run test
    ```

    From the browser

    ```
    http://m.icro.be/tests
    http://localhost/microbe/tests
    ```
```

**Comment by GrimmOutlook** [comment]
I went to work on this open issue (#103) but these changes have already been made in the ReadmeTestFix branch on the version I forked and cloned to my machine.  Did someone already send a PR?  Or am I missing something?

**Comment by mousemke** [comment]
Yup. @rcachero beat you to it with #104. We'll make more beginner friendly issues, but feel free to join us in our slack channel https://microbejs-slackin.herokuapp.com/

**Comment by GrimmOutlook** [comment]
OK, thanks for your prompt response and for creating beginner-friendly issues!
