### ISSUE TITLE
Use global object instead of query selector for IDs

### ISSUE THREAD

**Issue by AvraamMavridis** [sociomantic/microbe#105]
I am not 100% sure but I think this can improve the performance in some case:

Every time you add an id attribute to an element in an HTML page, that id becomes a global variable.
Check the console on this [codepen](http://codepen.io/AvraamMavridis/pen/XXmNqP?editors=101)

So every time the selector is `#id` you can access directly the global object instead of using the querySelector, and if is something like `#id .someclass` you can get the docFragment from the `#id` and look for the .someclass only on that part instead of the whole document.

I think this will improve the performance since you will avoid the call to the querySelector, but I am not 100% sure. If you have time you can investigate on that :)

**Comment by mousemke** [comment]
nice find.  how cross browser is that?

**Comment by mousemke** [comment]
i'm also a bit apprehensive about relying on a global that could be situationally overwritten

**Comment by mousemke** [comment]
http://codepen.io/anon/pen/BjoQOp?editors=101

**Comment by AvraamMavridis** [comment]
Yap, that's true. I am not sure either. I just saw it and thought to share it, in case it is useful :smile_cat:

**Comment by mousemke** [comment]
i'll dig deeper

**Comment by AvraamMavridis** [comment]
;)

**Comment by AvraamMavridis** [comment]
Closing the issue..

![download](https://cloud.githubusercontent.com/assets/283690/11779058/22a3235c-a259-11e5-9c67-b0241630595f.png)
![download2](https://cloud.githubusercontent.com/assets/283690/11779059/22a6d862-a259-11e5-9280-48f432c80f26.png)
