### ISSUE TITLE
discussion: replace wiki

### ISSUE THREAD

**Issue by jason-braun-sociomantic-mouse** [sociomantic/microbe#66]
we should get rid of the wiki as it is and just link to the site (m.icro.be) as it's silly to try to keep both up to date.  maybe use the site as a general usage site and have the wiki be for developers (coding standards/ whatever)

**Comment by jason-braun-sociomantic-mouse** [comment]
@nicolas-brugneaux-sociomantic i'm doing this.  see any issues with it?

**Comment by nicolas-brugneaux-sociomantic** [comment]
do it! :shipit:
