### ISSUE TITLE
add gitter && travis-ci

### ISSUE THREAD

**Issue by jason-braun-sociomantic-mouse** [sociomantic/microbe#67]
now that the repo is open source we can use these tools, however they should be opened with a non-sociomantic account as they require an account to connect with them.  to do this @mousemke and/or @nicolasbrugneaux need admin access to the repo.  This should happen before official release.

@leandro-lucarella-sociomantic @daniel-neubauer-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
OK, so now that the repo is public, the external-microbe doesn't make much sense as a read-only team. I will convert it in an admin team, so @mousemke and @nicolasbrugneaux has admin access to the rerpo.

**Comment by leandro-lucarella-sociomantic** [comment]
I made @mousemke also a team maintainer also for the external-microbe team.

**Comment by jason-braun-sociomantic-mouse** [comment]
Gitter added

https://github.com/sociomantic/microbe/pull/79
https://gitter.im/sociomantic/microbe?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link

**Comment by mousemke** [comment]
(0.4.13) travis ci is added gitter is removed as redundant (slack)
