### ISSUE TITLE
Docs lack examples

### ISSUE THREAD

**Issue by luminarious** [sociomantic/microbe#81]
Always interested to learn more about minimal libraries, especially if they claim to render jQuery obsolete or somesuch. But in its current state, I learned more from the github readme than the website docs.. :/

**Comment by jason-braun-sociomantic-mouse** [comment]
proposed doc syntax changes. @luminarious would this work better?

in code:
![15-09-23 14-51-50](https://cloud.githubusercontent.com/assets/4903570/10045429/e3420eb2-6202-11e5-9aa6-e338525cd7bf.png)

in /doc:
![15-09-23 14-52-21](https://cloud.githubusercontent.com/assets/4903570/10045434/ee3be3c4-6202-11e5-94c7-828908b1f846.png)

**Comment by luminarious** [comment]
Definite improvement! For future inspiration, Ramda is a favourite of mine both for functionality and design: http://ramdajs.com/0.17/docs/

**Comment by jason-braun-sociomantic-mouse** [comment]
they use dox.  definitely something to move into for the future, but we'd need to make a site to read the json.  i'll finish the comment examples for now, but definitely future formatting

to do:
selectorEngine/root
selectorEngine/core
selectorEngine/pseudo
