### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by yksikaksikolme** [sociomantic/microbe#83]
Awesome lib. Thanks a lot. 
I would like to use it as a bower module. 
Please add the support.

**Comment by mousemke** [comment]
https://github.com/sociomantic/microbe/commit/2dda7fe95445495013026bb84941d8719424060b
https://github.com/sociomantic/microbe/commit/be028f276991b28b4f271d3ef2bace8d100bc5cd
https://github.com/sociomantic/microbe/commit/63423c91fd6326c6cc1c27cdbb96df542bff75ae

```
bower install microbejs
```

enjoy!
