### ISSUE TITLE
Add new Slack "team" to the website.

### ISSUE THREAD

**Issue by dilkROM** [sociomantic/microbe#84]
The URL is microbejs.slack.com. Lets not forget to keep GitHub integrations turned off until we've spoken with Sociomantic about the appropriate way to do so (or researched it ourselves).

<edited:url spells - mouse>

**Comment by mousemke** [comment]
slackin server https://github.com/rauchg/slackin started at https://microbejs-slackin.herokuapp.com/

**Comment by mousemke** [comment]
closes with https://github.com/sociomantic/microbe/commit/3c1f6812ff55be824360170de615e00375a10c4e
