### ISSUE TITLE
Fix readme links to open in new tab

### ISSUE THREAD

**Issue by mousemke** [sociomantic/microbe#87]
In the spirit of learning how to use Git and Pull requests (PRs) <a href="https://twitter.com/yourfirstpr" target="_blank">@yourfirstpr</a>, this issue should be approachable for anyone. This should be a fairly straight forward change and will not effect the UI or functionality of the component. It's what we'd consider a "no harm" change. Here's what you need to do:

1 ) Fork the repo
2 ) Clone the repo to your local machine
3 ) Switch to the ReadmeLinkFix branch
3 ) Open up README.md in your favorite editor
4 ) Change the links (below)
5 ) Commit your changes to the file
5 ) Pull the repo.  This makes sure your branch is up to date before pushing your changes.
6 ) Push your changes to your fork
7 ) Create a PR and include Fixes #87 in the message
8 ) Get merged and celebrate :tada:

The Change
=========

In ./README.md, right above the change logs, replace this:
```
+ Twitter:        [@microbejs](https://www.twitter.com/microbejs)
+ Email:          [hello@m.icro.be](hello@m.icro.be)
+ Web:            [http://m.icro.be](http://m.icro.be/)
+ Git:            [https://github.com/sociomantic/microbe/](https://github.com/sociomantic/microbe/)
+ IRC ([freenode](https://kiwiirc.com/client/chat.freenode.net:+6697/#microbe)): #microbe
```

with this:

```
+ Twitter:        <a href="https://www.twitter.com/microbejs" target="_blank">@microbejs</a>
+ Email:          [hello@m.icro.be](hello@m.icro.be)
+ Web:           <a href="http://m.icro.be/" target="_blank">http://m.icro.be/</a>
+ Git:             <a href="https://github.com/sociomantic/microbe/" target="_blank">https://github.com/sociomantic/microbe/</a>
+ IRC           <a href="https://kiwiirc.com/client/chat.freenode.net:+6697/#microbe">freenode #microbe</a>
```

By replacing the Markdown with anchor tags, they will now open in a new window.

**Comment by Charlotteis** [comment]
Hello @mousemke! Thanks so much for this (I am creator of @yourfirstpr). Will be tweeting this out tomorrow :)
