### ISSUE TITLE
Missing array methods

### ISSUE THREAD

**Issue by AvraamMavridis** [sociomantic/microbe#88]
I am referring to methods like `Microbe.core.of, Microbe.core.join, Microbe.core.filter` etc. in the [array.js](https://github.com/sociomantic/microbe/blob/master/src/selectorEngine/array.js) file

e.g.
```
Microbe.core.of  = function(){ return Array.of ? Array.of : function(){ return Array.prototype.slice.call(arguments) }}();
```

 If this is a meaningful issue I can send the PR.

**Comment by mousemke** [comment]
sounds good.  i see no reason not to add compatibility with other native methods.

**Comment by jason-braun-sociomantic-mouse** [comment]
merged.  waiting on tests
