### ISSUE TITLE
CSS should accept objects

### ISSUE THREAD

**Issue by jason-braun-sociomantic-mouse** [sociomantic/microbe#94]
µ( _selector ).css() should accept object.  In addition to passing pre-built objects, why type
```
µ( _selector ).css( 'background-color', '#000' );
µ( _selector ).css( 'color', '#fff' )
```

when you can type
```
µ( _selector ).css( {  'color' : '#fff', 'background-color' : '#000'  } );
```

In the spirit of learning how to use Git and Pull requests (PRs) <a href="https://twitter.com/yourfirstpr" target="_blank">@yourfirstpr</a>, this issue should be approachable, though it does require some coding. This should be a fairly straight forward change and will add small functionality to microbe. It's what we'd consider a "low risk" change since it's only affecting a single module

This does not need to be done exactly as shown, but is intended to get more comfortable with git, pull requests, and give a peek into how microbe works.

Here's what you need to do:

1 ) Fork the repo
2 ) Clone the repo to your local machine
3 ) Switch to the `cssAcceptsObjects` branch
4 ) install the dependencies with `npm i`
3 ) Open up src/modules/elements.js in your favorite editor
4 ) Check if `_property` is an object.  change line 167 to 
```
var isObject = Microbe.isObject( _property );

```
5 ) allow the set css function to recieve a value. change line 169
```
var _setCss = function( _elm, _v )
```
but the css needs to accept this or the main value.  change line 173 to
```
_elm.data.css[ _property ]  = _v || _value;
```
6 ) line 183 should now be available if it is an object:
```
if ( _value || _value === null || _value === '' || isObject )
```
7 ) then, just inside that if statement (line 185), make the if statement to catch the object 
```
            if ( isObject )
            {
                for ( var prop in _property )
                {
                    this.css( prop, _property[ prop ] );
                }

                return this
            }
```
8 ) Save the file
9 ) open up tests/unit/elements.js
10 ) write a test for css recieving an object (line 153)
```
        µTarget.css( { 'background-color' : 'rgb(0, 255, 0)', 'color' : '#fff' } );
        assert.equal( µTarget[0].style.backgroundColor, 'rgb(0, 255, 0)', 'css object processed' );
```
11 ) run `npm run build` to build all the dist files and the tests.  this will also test the files.
      IF THIS FAILS, dont worry!  Just open the local test page in `tests/index.html` and see what's wrong, then recheck your code  
12 ) Once everything runs smoothly, commit your changes.
13 ) Pull the repo.  This makes sure your branch is up to date before pushing your changes.
14 ) Push your changes to your fork
15 ) Create a PR and include Fixes #94 in the message
16 ) Get merged and celebrate :tada:

**Comment by mousemke** [comment]
merged into branch microbe0.4.14
